---
- hosts: localhost
  connection: local
  become: true
  vars:
  tasks:
    - name: Update APK Cache
      apk:
        update_cache: yes

    - name: Installing Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: Installing Pre-Req Packages
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'curl'
        - 'mysql-client'
        - 'py-mysqldb'

    - name: Installing MySQL Server
      apk:
        name: "mysql"
        state: "present"
      register: "mysql_installed"

    - name: Configuring MySQL Listen Address
      replace:
        dest: "/etc/mysql/my.cnf"
        regexp: "^bind-address"
        replace: "#bind-address"
      when: mysql_installed.changed

    - name: Removing /var/lib/mysql
      file:
        path: "/var/lib/mysql"
        state: "absent"

    - name: Re-Creating /var/lib/mysql
      file:
        path: "/var/lib/mysql"
        state: "directory"
        owner: "mysql"
        group: "mysql"

    - name: Checking If /run/mysqld Exists
      file:
        path: "/run/mysqld"
        state: "directory"
        owner: "mysql"
        group: "mysql"
